name: Hello_World workflow
on:
  push:
    branches:
      -practice
  # pull_request:
  #   branches:
  #     -main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: python time.py
        shell: bash
